### ISSUE TITLE
Migrate to Node.js native test runner

### ISSUE THREAD

**Issue by fraxken** [fraxken/sec-literal#28]
Remove tape and related packages to use the Node.js native test runner.

https://nodejs.org/api/test.html

[i18n](https://github.com/NodeSecure/i18n) and [utils](https://github.com/NodeSecure/utils) has been migrated few days ago (so do not hesitate to check the scripts and tests).

> **Note** cross-env is probably not required anymore in scripts.

**Comment by clbcky** [comment]
Je prends !

**Comment by fraxken** [comment]
@clbcky Are you on it?
